### ISSUE TITLE
Pass Server-Timing info headers in new Chrome dev tool

### ISSUE THREAD

**Issue by Remiz** [jazzband/django-debug-toolbar#1045] opened 2018-02-15 18:04 UTC
Chrome dev tools recently got these new Server-Timing headers, that would be great if django-debug-toolbar could pass the information it already has that way too.

https://ma.ttias.be/server-timings-chrome-devtools/

**Comment by matthiask** [comment] 2018-02-16 10:02
I didn't have the time to test and review #928 yet. This is a pull request which should add support for this feature. It would be great if you could test the code in the pull request and report back whether it worked or not!

Closing this issue as a duplicate of the PR. Thanks!

**Closed by matthiask** 2018-02-16 10:02 UTC
