### ISSUE TITLE
Please integrate the Postgres Explain Visualizer tool

### ISSUE THREAD

**Issue by paddymul** [jazzband/django-debug-toolbar#1044] opened 2018-02-06 21:19 UTC
I came across this helpful postgres utility for understanding explain queries.  Integrating this into the django debug toolbar would make optimizing queries easier.   I would really appreciate it if someone could figure out how to integrate it.
http://tatiyants.com/postgres-query-plan-visualization/

**Comment by matthiask** [comment] 2018-09-06 06:35
Duplicate of #1042

**Closed by matthiask** 2018-09-06 06:35 UTC
