### ISSUE TITLE
Add kparams to callproc

### ISSUE THREAD

**Issue by brycecaine** [jazzband/django-debug-toolbar#1189] opened 2019-07-31 13:39 UTC
I couldn't find an issue that requests this, so forgive me if there is one and I missed it.

Django's version of `callproc` supports a `kparams` keyword argument:

https://docs.djangoproject.com/en/2.2/topics/db/sql/#django.db.models.CursorWrapper.callproc

It would be awesome if `django-debug-toolbar` supported `kparams` as well:

https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/sql/tracking.py#L188

I might attempt a pull request if I had more time, but I wanted to at least start the conversation.

Thank you so much for an amazing tool! I love the insight `django-debug-toolbar` provides.

**Comment by matthiask** [comment] 2019-08-02 12:57
Definitely makes sense.

**Comment by matthiask** [comment] 2023-01-20 19:48
I think this is a duplicate of #907

**Closed by matthiask** 2023-01-20 19:48 UTC
Labels: Improvement
