### ISSUE TITLE
Huge amount of store_id access has been raised

### ISSUE THREAD

**Issue by heavenshell** [jazzband/django-debug-toolbar#1725] opened 2022-12-21 14:40 UTC
Hello. Thank you for great works.

I've update to v3.8.1 and found some issue.

When I access to SPA page, which access to server api using axios, 
huge amount of access(*) was recorded and Debug toolbar does not show any panel.
\* `http://localhost:8000/__debug__/history_sidebar/?store_id=03b13fc6002f4d11abd19ca4de7cb732`) 

Not SPA page(maybe not access to API server via JavaScript), does not happen.

Dose anyone else experienced the same problem?

v3.8.1

https://user-images.githubusercontent.com/56591/208930764-aef41a86-7a8b-464e-a6e2-903b65ee3b5c.mp4

v3.7.0 works fine.

https://user-images.githubusercontent.com/56591/208929306-f0a4241d-e7ae-4091-accc-f2f15f6f5ee7.mp4

I think this PR https://github.com/jazzband/django-debug-toolbar/pull/1685 was releated.

OS: macOS X
Django: 3.2.16
React: 17.0.2
axios: 0.27.2

Best regards.

**Comment by matthiask** [comment] 2023-01-20 19:54
Yes, that's almost certainly related to #1685. I'm wondering what's happening here though. I don't see those repeated requests (obviously) and I also work with more or less the same software as you do. Not using axios, but React, Django etc.

One hypothesis which comes to mind is that the toolbar may be loaded more than once and the window.fetch we're calling isn't actually the correct window.fetch but our own, so that we're looping infinitely? Or maybe React re-renders the toolbar because of the DOM change? (No idea why this would happen, though.) I assume that you're not using React to render the whole `<body>`?

**Comment by heavenshell** [comment] 2023-02-04 11:57
@matthiask Thank you for replay!

Humm, minimum code(below) did not reproduced.
Maybe my Application cause something wrong to debug tool bar.

```typescript
import axios from 'axios'

const Component = () => {
  axios.get('/api/me/') // Just get profile from Django app's endppint

  return <div>foo</div>
}

const App = () => (
  <Component />
)

render(<App />, document.getElementById('app'))
```

```python
urlpatterns = [
    path(
        'foo',
        TemplateView.as_view(template_name='a.html'),
        name='foo',
    ),
]
```

```htmldjango
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>sample</title>
    <script defer src="{% static 'app.js' %}"></script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```
app.js is hole React SPA application(build by webpack)

I don't have enough time to investigate this now.
(I freezed to old 3.7.0 version)
I'll look into it when I get some time.

It would be very happy if you could find out anything.

Thank you.

**Comment by tim-schilling** [comment] 2023-02-04 12:03
How often is it making API calls?

**Comment by tim-schilling** [comment] 2023-02-04 16:12
@heavenshell when investigating it, keep in mind [the toolbar does this patching to detect](https://github.com/jazzband/django-debug-toolbar/blob/main/debug_toolbar/static/debug_toolbar/js/toolbar.js#L281-L309) when an ajax request is made.

**Comment by skamansam** [comment] 2023-03-03 22:37
Just to show support, I am also having this issue with 3.8.1. It is happening on DRF views and drf-yasg (swagger/redoc) views - basically all the django html views that show the toolbar.

My settings are:
```python
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]
MIDDLEWARE = MIDDLEWARE + [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]
INSTALLED_APPS = DEFAULT_APPS + ['debug_toolbar']
```

**Comment by tim-schilling** [comment] 2023-03-04 16:52
@skamansam it should be possible over set the `SHOW_TOOLBAR_CALLBACK` setting to a view that can determine if the view should be instrumented or not based on your own application's needs.

**Comment by heavenshell** [comment] 2023-09-20 03:43
FYI
When I remove ` 'debug_toolbar.panels.history.HistoryPanel',` from `DEBUG_TOOLBAR_PANELS`,
This issue does not raised(`django-debug-toolbar==4.2.0`)

**Comment by tim-schilling** [comment] 2023-10-05 19:21
@heavenshell I'm going to close this until there's a reproducible example.

**Closed by tim-schilling** 2023-10-05 19:21 UTC
