### ISSUE TITLE
Some String Has Truncated Before Model Save In  Releases Version==3.2.3

### ISSUE THREAD

**Issue by TryReboot** [jazzband/django-debug-toolbar#1543] opened 2021-12-14 15:28 UTC
#### I found some string was truncated in this function

```python
def strip_GeomFromEWKB(param):
    if isinstance(param, str):
        return param.lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
    return param
```

#### Related Pull Request

- https://github.com/jazzband/django-debug-toolbar/pull/1426

####  Minimally Reproducible Test Case

```python
In [8]: "botpy".lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
Out[8]: 'botp'

In [9]: "Botpy".lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
Out[9]: 'tp'
```

**Comment by tim-schilling** [comment] 2021-12-14 15:48
@TryReboot do you have an example of a query that is impacted by this?

**Comment by TryReboot** [comment] 2021-12-14 16:35
@tim-schilling  For example , you want to save a  string  into  some django model,  if this string include "y" or "e",  this string was truncated then  save into database.  I don't know if anyone else has same problem.

**Comment by TryReboot** [comment] 2021-12-14 16:46
@tim-schilling For example

```python
# the `name` is a `CharField` in `Company` model.
# I want to save a Company Object and `name`='botpy' 
company = Company.objects.create(id=1, name="botpy")
print(Company.objects.get(pk=company.id).name)
# result should be 'botpy' not 'botp'
Out[12]: botp
```

**Comment by tim-schilling** [comment] 2021-12-14 16:53
It sounds like the issue is when the parameter is not for a GIS query and it's stripping these characters still.

**Comment by matthiask** [comment] 2021-12-15 16:53
Oh damn. This should be `.removeprefix()` or `.removesuffix()`, not `.lstrip()` or `.rstrip()`. The latter uses a *set* of chars to remove.

(Respectively their implementation since the `remove*` methods only exist on Python 3.9 or better.)

**Comment by bellini666** [comment] 2021-12-15 19:56
Hey guys,

Wow, was getting crazy about this... Have some constraints that check that some `CharField` with `choices` has their value in exactly one of the choices, but the tests where passing fine, creating/updating the model in a shell was working fine, but when creating it in a request (django-admin/any other view) gave me the error. Examining the sql I notice that some characters were missing, for example "ecommerce" was appearing on sql as "commerc", "flat" as "fl", and even some names like "John Doe" as "John Do".

I don't use GIS in that specific project so it is not related to only GIS. I think it is important to give this a _very high priority on releasing a bugfix since someone could have the debug-toolbar enabled in a production code (even if in the middleware only), and he would for sure have issues with his data.

The problem caught my attention because, in the example above, "ecommerce" is an enum for me and I have a database constraint that checks this and don't let me type anything other than the valid values, and "commerc" is not one of those. But the fact that "John Doe" was written as "John Do" could easily pass silently. And like I said, unit tests are unlikely to ge this unless they are really testing the request itself (for me they didn't, specially because even when testing the requests, I only enable the toolbar's middleware for code running on manage.py itself)

**Comment by bellini666** [comment] 2021-12-15 19:58
Also, I saw that last release was released as `3.2.3`. Why not release it as `3.3`?

By only increasing the micro it looks like it is a release that only has bugfixes. By increasing at least the minor it makes it easy for people to know that "well, let me take a look at the changelog to check if there's something that I need to be aware of".

**Closed** 2021-12-15 20:34 UTC

**Comment by tim-schilling** [comment] 2021-12-15 20:35
> Also, I saw that last release was released as 3.2.3. Why not release it as 3.3?

As far as I knew, there were no issues with the project and it was all bug fixes.

**Comment by tim-schilling** [comment] 2021-12-15 21:02
@bellini666 thank you for escalating the issue. I likely would have waited until tomorrow to release 3.2.4 otherwise.

**Comment by bellini666** [comment] 2021-12-15 21:12
Hey @tim-schilling , np! Ty for acting that fast! :)
