### ISSUE TITLE
SQL Panel: + button is no longer functional in debug-tool-bar 3.2

### ISSUE THREAD

**Issue by caramdache** [jazzband/django-debug-toolbar#1434] opened 2021-01-14 15:22 UTC
Steps to reproduce:

1. Refresh a page
2. Open a the debug toolbar
3. Select the SQL panel
4. Press the + button for an SQL request

Result:
- Nothing happens, the + button is not responsive (whatever the SQL request)
- (There is no such issue in earlier versions, including 2.2, 3.0, 3.1.)

Expected result:
- The + button should show the details of the SQL request

Environement:
- django 3.1.5
- debug-toolbar 3.2
- python 3.6.8

**Comment by tim-schilling** [comment] 2021-01-15 19:34
I can't reproduce this using our example project. The only difference is that I used python 3.6.9.

Can you please check the browser's console to see if there is any information being rendered there about javascript errors?

**Comment by caramdache** [comment] 2021-01-29 11:46
I've recently setup a new virtual environment and moved to Python 3.9.1.

I confirm the issue is still present (in 3.2, but not in 3.1). There's nothing special in the console, just the usual stuff.

I noticed there is no event attached to the + button. But I discovered that this is the same in 3.1. I don"t know how you trigger the behaviour.

**Comment by caramdache** [comment] 2021-01-29 11:47
I guess there must be some code difference between 3.2 and 3.1 that could explain the difference.

**Comment by tim-schilling** [comment] 2021-01-29 12:17
Can you check to see if the SQL panel's JavaScript file loaded property via
the network panel of the browser's dev tools?

Are you using windows?

**Comment by caramdache** [comment] 2021-02-10 17:03
Problem solved! It appears that I had not upgraded the static files for a while. 

BTW, I did not find instructions on how to install the static files in the documentation:
    https://django-debug-toolbar.readthedocs.io/en/latest/installation.html

Did I miss something?

**Comment by matthiask** [comment] 2021-02-10 17:09
Good point, this may not be obvious. Here's a pull request which may (or may not) fix this: https://github.com/jazzband/django-debug-toolbar/pull/1449

**Comment by tim-schilling** [comment] 2021-02-10 17:19
@caramdache Can you explain what you mean by "It appears that I had not upgraded the static files for a while." Were you running this locally with `DEBUG = True` and the static files appended to your urls such that the static files are served as a part of `runserver`?

**Comment by caramdache** [comment] 2021-02-11 14:06
I don't use `runserver` but Apache with `DEBUG = True` when necessary.  I also don't use `collectstatic`. I have other ways of updating that seems that dates back from a very, very early release of Django.

**Comment by tim-schilling** [comment] 2021-02-11 14:11
@caramdache Are you running this locally or on a remote/production server?

**Comment by caramdache** [comment] 2021-02-11 15:49
On a remote production server.

**Comment by tim-schilling** [comment] 2021-02-11 16:03
Alright cool thank you for the information. I would argue that the issue you experienced is not due to anything specific to the toolbar. Part of a Django app's deployment process should include running `collectstatic` at some point. It is specifically needed when the local static files have changed or a dependency has changed (such as the toolbar update).

@matthiask I'm torn on whether to include that bit of information in the installation docs. What's your take? The typical use case is for local development. Folks have been using the toolbar on production environments more and more, so maybe we need a production/remote specific section of the docs?

**Comment by matthiask** [comment] 2021-02-11 16:13
@tim-schilling Outdated assets are a semi-regular occurrence with the debug toolbar it seems. I think we should mention the need to run collectstatic when not using the runserver. With a big caveat, of course – I still wouldn't recommend running the debug toolbar in a non-development environment)

**Comment by tim-schilling** [comment] 2021-02-11 16:18
Alright, that works for me.

**Comment by caramdache** [comment] 2021-02-22 17:16
> I still wouldn't recommend running the debug toolbar in a non-development environment

@matthiask It's a company internal server/service, so the risk is low.

**Comment by tim-schilling** [comment] 2021-04-24 14:53
@matthiask I'm thinking we close this issue without changes to the documentation. I don't think we have the availability to make the toolbar production ready. I'd also argue that's where APMs should come into the picture for a developer. We do not take anything away from Django devs either by not providing a toolbar that can run in production. Afterall, if a dev can enable the toolbar on a remote server, they likely point their local machine to that database/cache/etc and recreate the issue without exposing the toolbar's functionality to any user.

Additionally regarding availability and resources, I think they would be better suited to supporting Django Channels and ASGI.

**Comment by matthiask** [comment] 2021-04-24 20:38
@tim-schilling Yes, I agree. I closed #1449 (the documentation PR). Maybe a caveat would be in order to only install django-debug-toolbar on servers without worthless data only.

**Closed** 2021-04-24 20:46 UTC
