### ISSUE TITLE
Refused to get unsafe header "djdt-store-id"

### ISSUE THREAD

**Issue by slyapustin** [jazzband/django-debug-toolbar#1633] opened 2022-05-30 09:46 UTC
Got that error in the Chrome console.

<img width="652" alt="Screen Shot 2022-05-30 at 11 45 10" src="https://user-images.githubusercontent.com/370774/170965843-e7eda6d7-5611-49df-8e10-8549da1a106f.png">
<img width="633" alt="Screen Shot 2022-05-30 at 11 45 23" src="https://user-images.githubusercontent.com/370774/170965856-75aa38a2-54bc-45ff-a9f6-eb91ab358eb9.png">
Django  3.2.13
debug_toolbar 3.4.0

**Comment by jottenlips** [comment] 2022-06-16 14:33
We are also getting this on Django 4

**Comment by tim-schilling** [comment] 2022-08-29 00:51
Closing as duplicate of #1647 and closed in #1651

**Closed by tim-schilling** 2022-08-29 00:51 UTC

**Comment by tim-schilling** [comment] 2022-10-11 09:09
Is this running locally? And/or does it happen to be in an iframe?

**Comment by pbadeer** [comment] 2022-10-13 13:38
I was getting this error locally, but it was not in an iframe. It was causing front-end tests to fail and ended up driving us to remove DJDT from our project.

**Comment by pbadeer** [comment] 2022-11-11 19:23
We were on 3.4 when we removed it from the project.
