### ISSUE TITLE
UnicodeDecodeError in get_staticfiles_finders()

### ISSUE THREAD

**Issue by guettli** [jazzband/django-debug-toolbar#934] opened 2017-04-28 12:54 UTC
I have a filename which contains utf8:

b = 'f\xc3\xbcr-Elise.png' (für-Elise.png)
path = '/home/issues_vums_d/src/issues-vums/issues_vums/static/issues_vums/screenshots/scan'

This results in this exception in get_staticfiles_finders()

{{{
Environment:

Request Method: GET
Request URL: 

Django Version: 1.9.9
Python Version: 2.7.12
Installed Applications:
[u'dal',
 u'dal_select2',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.admin',
 u'django.contrib.sites',
 u'django.contrib.staticfiles',
 u'reversion',
 u'colorful',
 u'djangotools',
 u'djangotools.box',
 u'djangotools.jsonstore',
 u'djangotools.jwt_auth',
 u'djangotools.texts',
 u'djangotools.autocomplete',
 u'djangotools.tree',
 u'djangotools.attachment',
 u'django_jquery',
 u'selectable',
 u'selectable_tbz',
 u'issues',
 u'tbzdblogging',
 u'polymorphic',
 u'yui',
 u'ckeditor',
 u'debug_toolbar',
 u'rest_framework',
 'issues_vums',
 u'issues_workflowtest',
 'issues_isu',
 'modwincontrol',
 'issues_modarch',
 'issues_emailcheck',
 'tbzgetusersfromremotesystem',
 'htmltemplate']
Installed Middleware:
[u'djangotools.middleware.XUACompatibleMiddleware',
 u'djangotools.middleware.HandleExceptionMiddleware.HandleExceptionMiddleware',
 u'django.middleware.http.ConditionalGetMiddleware',
 u'djangotools.middleware.ProfileMiddleware.ProfileMiddleware',
 u'djangotools.middleware.CheckHTMLMiddleware.CheckHTMLMiddleware',
 u'djangotools.middleware.SQLLogMiddleware.SQLLogMiddleware',
 u'djangotools.middleware.FormDictMiddleware.FormDictMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'djangotools.middleware.ApiBasicAuthMiddleware.ApiBasicAuthMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware',
 u'reversion.middleware.RevisionMiddleware',
 u'djangotools.jwt_auth.middleware.JSONWebTokenAuthMiddleware',
 u'djangotools.middleware.GlobalRequestMiddleware.GlobalRequestMiddleware',
 u'djangotools.utils.mediautils.RequestMediaMiddleware',
 u'djangotools.utils.has_perm.HasPermMiddleware',
 u'djangotools.utils.sessionutils.MessageCookieMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'djangotools.middleware.HttpQueueStartMiddleware.HttpQueueStartMiddleware',
 u'djangotools.middleware.ReloadMiddleware.ReloadMiddleware',
 u'djangotools.middleware.RequestDurationMiddleware.RequestDurationMiddleware',
 u'issues.middleware.issuesMiddleware.issuesMiddleware',
 u'djangotools.middleware.FakeUserMiddleware.FakeUserMiddleware']

Traceback:

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  235.                 response = middleware_method(request, response)

File "/home/issues_vums_d/local/lib/python2.7/site-packages/debug_toolbar/middleware.py" in process_response
  129.                 panel.generate_stats(request, response)

File "/home/issues_vums_d/local/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py" in generate_stats
  127.             'staticfiles_finders': self.get_staticfiles_finders(),

File "/home/issues_vums_d/local/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py" in get_staticfiles_finders
  138.             for path, finder_storage in finder.list([]):

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py" in list
  148.                 for path in utils.get_files(storage, ignore_patterns):

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py" in get_files
  40.         for fn in get_files(storage, ignore_patterns, dir):

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py" in get_files
  40.         for fn in get_files(storage, ignore_patterns, dir):

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py" in get_files
  40.         for fn in get_files(storage, ignore_patterns, dir):

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py" in get_files
  28.     directories, files = storage.listdir(location)

File "/home/issues_vums_d/local/lib/python2.7/site-packages/django/core/files/storage.py" in listdir
  300.             if os.path.isdir(os.path.join(path, entry)):

File "/home/issues_vums_d/lib/python2.7/posixpath.py" in join
  73.             path += '/' + b

Exception Type: UnicodeDecodeError at /query/export/xlsx/
Exception Value: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
}}}

Is there a way to support utf8 file names?

**Comment by matthiask** [comment] 2017-05-02 11:35
Hmm, the exception happens deep inside the staticfiles app. I'm wondering why/whether `collectstatic` would work? Maybe setting `LANG=en_US.UTF-8`, `LC_ALL=en_US.UTF-8` in the server process would help?

(I also created a `für-elise.png` file in one of my projects and tested both locally and on the server and everything *seemed* to work fine.)

**Comment by jdufresne** [comment] 2020-09-27 19:10
It looks like you're using Python 2 and Django 1.9 which are no longer supported. Recent versions of Django and Debug Toolbar are Python 3 only and support UTF8 filenames. Can you please try to upgrade and test again? Closing for now as the issue looks outdated, but if you can reproduce, please reopen.

**Closed by jdufresne** 2020-09-27 19:10 UTC
