### ISSUE TITLE
INTERNAL_IPS causes expected str, bytes or os.PathLike object, not Path

### ISSUE THREAD

**Issue by elcolie** [jazzband/django-debug-toolbar#1007] opened 2017-11-08 11:14 UTC
django==1.11.7
djangorestframework-jwt==1.11.0
djangorestframework==3.7.3
python3.6.3

https://gist.github.com/elcolie/dffe291e6f96f2a5eef320d9a1f83173
https://gist.github.com/elcolie/97be2452a556ac0e49f66499e6112cc2

I uses `local.py` override the `base.py`
Without `INTERNAL_IPS = ['127.0.0.1']`
I can work every page normally.

**Problem:**
When I add `INTERNAL_IPS = ['127.0.0.1']`
I can see the `dj toolbar` only the first page of API
![screenshot-2017-11-8 page not found at](https://user-images.githubusercontent.com/18206728/32545984-1a487484-c4b0-11e7-9311-de7635ba7733.png)

When I go to deeper url for example `/api`
```bash
Internal Server Error: /api/
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 132, in process_response
    panel.generate_stats(request, response)
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/debug_toolbar/panels/templates/panel.py", line 217, in generate_stats
    'template_dirs': [normpath(x) for x in template_dirs],
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/debug_toolbar/panels/templates/panel.py", line 217, in <listcomp>
    'template_dirs': [normpath(x) for x in template_dirs],
  File "/Users/sarit/.pyenv/versions/3.6.3/lib/python3.6/posixpath.py", line 331, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not Path
"GET /api/ HTTP/1.1" 500 111041
```

Am I misconfigure something?

**Reference:**
https://django-debug-toolbar.readthedocs.io/en/stable/installation.html

**Comment by matthiask** [comment] 2017-11-13 19:52
Hmm, I never tried running with `Path` objects; we're still using `os.path.*` functions with strings everywhere. It seems django-environ's Path objects are not PathLike yet. I'd argue that this is a django-environ bug, not a bug in django-debug-toolbar. Also, see here:

https://github.com/joke2k/django-environ/issues/106
https://github.com/joke2k/django-environ/pull/107

I'm closing this issue; please reopen if you disagree.

**Closed by matthiask** 2017-11-13 19:52 UTC

**Comment by elcolie** [comment] 2017-11-14 02:52
Understood. I will wait until `django-environ` bug is gone.

**Comment by inconnu259** [comment] 2017-12-05 22:53
So have you found a solution to patch this ?

**Comment by matthiask** [comment] 2017-12-06 09:20
Not in django-debug-toolbar, no, since the bug exists in django-environ.

Maybe have a look at the following links in case the problem isn't resolved:
https://github.com/matthiask/speckenv
https://github.com/kennethreitz/dj-database-url
https://github.com/ghickman/django-cache-url
https://github.com/migonzalvar/dj-email-url

Or use `base.path(...).__str__()` instead of `base.path(...)` with django-environ, so that the Django configuration contains strings instead of `Path` objects.
