### ISSUE TITLE
Error on compilemessages due to translations from django-debug-toolbar

### ISSUE THREAD

**Issue by berzi** [jazzband/django-debug-toolbar#1862] opened 2023-12-04 15:27 UTC
The command `django-admin compilemessages` fails when I have `django-debug-toolbar` installed (I tried both 4.1.0 and 4.2.0 which is currently the latest release).

The full error is as follows (the `#0` and timing at the start of each line are due to docker compose and should be irrelevant for the issue):

```
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/pt_BR/LC_MESSAGES/django.po:151: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.203 msgfmt: found 2 fatal errors
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/sv_SE/LC_MESSAGES/django.po:81: number of format specifications in 'msgid' and 'msgstr' does not match
#0 5.203 msgfmt: found 1 fatal error
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/sk/LC_MESSAGES/django.po:162: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.203 msgfmt: found 4 fatal errors
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/ca/LC_MESSAGES/django.po:80: number of format specifications in 'msgid' and 'msgstr' does not match
#0 5.203 msgfmt: found 1 fatal error
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/pt/LC_MESSAGES/django.po:80: number of format specifications in 'msgid' and 'msgstr' does not match
#0 5.203 msgfmt: found 1 fatal error
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/fi/LC_MESSAGES/django.po:150: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.203 msgfmt: found 2 fatal errors
#0 5.203 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/zh_CN/LC_MESSAGES/django.po:146: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.203 msgfmt: found 1 fatal error
#0 5.212 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/pl/LC_MESSAGES/django.po:155: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.212 msgfmt: found 3 fatal errors
#0 5.213 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/uk/LC_MESSAGES/django.po:83: number of format specifications in 'msgid' and 'msgstr' does not match
#0 5.213 msgfmt: found 1 fatal error
#0 5.215 Execution of msgfmt failed: /tmp/.venv/Lib/site-packages/debug_toolbar/locale/cs/LC_MESSAGES/django.po:154: a format specification for argument 'cache_calls', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
#0 5.215 msgfmt: found 3 fatal errors
```

All I can find from researching the error is that this error is due to plurals being used incorrectly, but the lines I checked from the traceback don't use any syntax for plurals and in fact seem unrelated to each other (sometimes they're the same place, like for catalan and portuguese, but for other languages they point to completely different places).

Needless to say I did not modify the package after installing it, and all this is running in a clean Docker container that other colleagues have been using for ages, except I'm on Windows (but the container isn't). Any clue why this isn't working for me?

**Comment by matthiask** [comment] 2023-12-04 18:54
I see a fuzzy translation at the first location:
![image](https://github.com/jazzband/django-debug-toolbar/assets/2627/5ef465bb-0d04-4dc8-a981-4fc24bd536f7)

No idea why the fuzzy translation wouldn't simply be ignored.

**Comment by berzi** [comment] 2023-12-05 08:02
Apologies, the command actually includes `--use-fuzzy`. Still, I don't see why this should make it fail.

**Comment by matthiask** [comment] 2023-12-05 14:13
@tim-schilling Yes. I don't know why that would be a fatal error when the whole translation is marked as `fuzzy` though.

**Comment by tim-schilling** [comment] 2023-12-13 00:21
@berzi would you be able to create a minimal project that reproduces this effect?

**Comment by berzi** [comment] 2023-12-13 07:48
> @berzi would you be able to create a minimal project that reproduces this effect?

Unfortunately I don't think so, the error comes from an old and complex project from my company and it would be quite time-consuming to try and recreate it.

**Comment by tim-schilling** [comment] 2023-12-13 12:22
@berzi i understand, but from what we can see everything should be working. The only way for us to debug this would be to reproduce it. Since this work would most benefit you in particular, it feels reasonable to ask you to help us with that effort. 

If you don't have time that's totally understandable.

This is a low priority for us because it's an undefined amount of work for an undefined amount of benefit.

**Comment by berzi** [comment] 2023-12-13 12:26
> @berzi I understand, but from what we can see everything should be working. The only way for us to debug this would be to reproduce it. Since this work would most benefit you in particular, it feels reasonable to ask you to help us with that effort.
> 
> If you don't have time that's totally understandable.
> 
> This is a low priority for us because it's an undefined amount of work for an undefined amount of benefit.

I understand that. The error doesn't block me at the moment so it's low priority for me as well. If I get any new clue or get the time to reproduce the error I'll post here again.

I'm fairly sure it has something to do with Windows, since I'm the only one of all my colleagues who worked and this and had this issue, but there's also many outdated things all along the pipeline (the Django version, the Docker Compose version...) so who knows.

**Comment by tim-schilling** [comment] 2023-12-13 12:31
That's actually a good place to start. What versions of python, docker
compose and Django are you using?

**Comment by berzi** [comment] 2023-12-13 12:37
Docker Compose: 3.7
Python: 3.10
Django: 3.2.20
Django debug toolbar: tried both 4.1.0 and 4.2.0

gettext and other dependencies are installed with the following command:
```shell
apt-get install --no-install-recommends -y \
      gettext \
      libgettextpo-dev \
      procps \
      locales
```

**Comment by matthiask** [comment] 2024-07-05 14:37
I just tried again with and without `--use-fuzzy` and I cannot reproduce this. I'm going to close the issue, but *please* reopen if you find a way to make this reproducible.  Thank you!

**Closed by matthiask** 2024-07-05 14:37 UTC
