### ISSUE TITLE
SQL panel: data of query (stored in a HTML hidden field) leaks into action column

### ISSUE THREAD

**Issue by karolyi** [jazzband/django-debug-toolbar#1756] opened 2023-04-05 13:28 UTC
Hey,

I'm using the latest toolbar, and I noticed that somehow the 'action' column of the SQL panel sometimes contains some SQL-looking code, that pushes every other columns to the smallest available width, this using the panel unreadable. A screenshot:

![image](https://user-images.githubusercontent.com/987055/230094292-6f0c6f55-247b-42d5-8f83-f62ba391bcc6.png)

Upon looking into it with devtools (I'm using Librewolf), it seems the leaking text should be stored in the value of a html hidden input field, but somehow only part of it does:

![image](https://user-images.githubusercontent.com/987055/230094602-51a81fdb-b3ae-4d3c-85e9-68bf4c17e0e3.png)

Right now I have no idea as to what's happening here. I'm using a pretty default toolbar config, with nothing changed.

I'm open to questions to figure out what this is.

**Comment by tim-schilling** [comment] 2023-04-05 13:33
Thanks for the report @karolyi! If you have time to identify the fix or open a PR, that would go a long way to getting a fix out quickly.

**Comment by karolyi** [comment] 2023-04-05 13:34
Hey,

unfortunately I don't have time to make myself acquainted with the inner workings of django-debug-toolbar, but I'm happy to provide more information upon request.

**Comment by matthiask** [comment] 2023-04-05 14:14
I'm unable to reproduce this. Can you provide additional details, e.g. the database engine and the versions of involved packages you're using? (Django, sqlparse etc.)?

**Comment by karolyi** [comment] 2023-04-05 14:17
Hey,

of course.

The database engine is MariaDB, with using `mysqlclient==2.1.1`, `sqlparse==0.4.3`, `Django==4.1.8`, and `django-debug-toolbar==4.0.0`.

If there's anything else you need, let me know.

**Comment by matthiask** [comment] 2023-04-05 14:20
... urlsafe base64 encoding completely avoids the problems around escaping, that's why I'm suggesting this.

**Comment by karolyi** [comment] 2023-04-05 16:36
If my opinion counts, I support whatever works. :)

**Comment by tim-schilling** [comment] 2023-07-01 21:43
@karolyi This is likely related to django-jinja rendering a hidden input with JSON inside of it. Can you share the relevant information to reproduce your project? Your django-jinja set up refers to a number of non-default extensions. I'm not familiar with jinja too much so we'll need your help recreating this environment.

Alternatively, you could create a small project that's a minimal example that reproduces the effect.

**Comment by karolyi** [comment] 2023-07-02 10:41
Hey,

at your service. :)

I've prepared a small test repo where you can reproduce the bug: https://gitea.ksol.io/karolyi/ddt-1756

Do a requirements install, and then migrate, and then a runserver. Then point your browser to `/test/`, reload once more (the first iteration will put a variable into the session DB the later requests use), and on second reload you'll be able to see the JSON data in the hidden field reachable with the CSS selector `.djdt-actions form[method=post] input[name=signed]`.

Hope I could help.

**Comment by tim-schilling** [comment] 2023-10-23 01:14
@karolyi I think this may be a browser issue. I can't reproduce this.

When I inspect the rendered HTML, it does appear to look like what you show, but when I go to copy it in the browser dev tools, it shows that it's properly HTML escaped:

```
{&quot;vendor&quot;: &quot;sqlite&quot;, &quot;alias&quot;: &quot;default&quot;, &quot;sql&quot;: &quot;SELECT \&quot;django_session\&quot;.\&quot;session_key\&quot;, \&quot;django_session\&quot;.\&quot;session_data\&quot;, \&quot;django_session\&quot;.\&quot;expire_date\&quot; FROM \&quot;django_session\&quot; WHERE (\&quot;django_session\&quot;.\&quot;expire_date\&quot; > '2023-10-23 01:12:38.091261' AND \&quot;django_session\&quot;.\&quot;session_key\&quot; = 'i0bw0vly2w12mp356fh042s6gyras4sg') LIMIT 21&q
...
```

I'm going to close this as won't fix unless you can identify where in our code it's breaking.

**Closed by tim-schilling** 2023-10-23 01:14 UTC
Labels: Bug

**Comment by karolyi** [comment] 2023-10-23 01:22
I'm gonna give this test another go tomorrow, but my hunch is the `'autoescape': False` setting.

**Comment by karolyi** [comment] 2023-10-23 16:18
So, as told, I gave it another go.

Now original page source doesn't contain the input[name=signed] field, I can only find it in the devtools, once I opened it and went to see the SQL queries.

The source that had the botched field before looks like this now:
```html
<div id="SQLPanel" class="djdt-panelContent djdt-hidden">
    <div class="djDebugPanelTitle">
      <button type="button" class="djDebugClose">×</button>
      <h3>SQL queries from 1 connection</h3>
    </div>
    <div class="djDebugPanelContent">
      
        <div class="djdt-loader"></div>
        <div class="djdt-scroll"></div>
      
    </div>
  </div>
```

The content before was in `div.djdt-scroll`. It's as if some JS code puts it there now, and doesn't come generated with the source.

Is there any setting that regulates this?

**Comment by tim-schilling** [comment] 2023-10-23 16:24
No, there's no setting that controls putting content in `div.djdt-scroll` as far as I know.

**Comment by karolyi** [comment] 2023-10-23 17:14
Weird.

So what should be the official way of putting the content in there? Is it via JS or should it come with the generated page?

It is really strange that now it ends up there by some kinda DOM manipulation logic, whereas it was generated before.
