### ISSUE TITLE
static file panel 400 bad request

### ISSUE THREAD

**Issue by jayground** [jazzband/django-debug-toolbar#992] opened 2017-09-22 02:25 UTC
1. **version**
Django 1.11.1
django-debug-toolbar 1.8

2. **my problem**
It loads static files on web browser without any problem in development env. I added django-debug-toolbar. Other panels of django-debug-toolbar works fine. But Just static file panel shows 400 bad request error.

![image](https://user-images.githubusercontent.com/30852958/30726760-bbe8c1ca-9f87-11e7-8e2c-d0378f26b620.png)

![image](https://user-images.githubusercontent.com/30852958/30726794-f5aa25fc-9f87-11e7-8964-2405281a0be5.png)

![image](https://user-images.githubusercontent.com/30852958/30726799-fff6e16c-9f87-11e7-86a8-5ef9c81e54ae.png)

3. **my code**
settings.py

```
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'src'), ] # there  are most of static files in this directory
```

urls.py
```

urlpatterns = [
    ...
]
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_URL)
```

**Comment by SayyamAhmed** [comment] 2020-04-11 17:36
I am facing exactly similar issue. Kindly anyone guide me through it ?  @jayground

**Comment by jdufresne** [comment] 2020-09-27 18:54
I cannot reproduce.

Do you see warnings or errors in the browser's JavaScript console? Any errors in the Django `runserver` output?

I'm closing as this issue is quite old and there have been some major releases since. If you can still reproduced, please feel free to reopen with more details.

**Closed by jdufresne** 2020-09-27 18:54 UTC

**Comment by rolandf** [comment] 2020-10-11 21:02
> I am facing exactly similar issue. Kindly anyone guide me through it ? @jayground

Maybe you reference a static file with a leading backslash that you need to remove to fix this.
Full explanation here: https://stackoverflow.com/a/64308943/2529847
